### ISSUE TITLE
Notice: Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by maheshwaghmare** [pedro-mendonca/Translation-Tools#2] opened 2020-06-12 05:42 UTC
Getting error after install and activate plugin:
```
Notice: Trying to access array offset on value of type bool in C:\xampp\htdocs\dev\wp-content\plugins\translation-tools\includes\class-ttools-options-general.php on line 138
```

Screenshot - https://i.imgur.com/cAwb3CZ.png

Line - https://github.com/pedro-mendonca/Translation-Tools/blob/master/includes/class-ttools-options-general.php#L137

Tried to send the PR but the code not found in which the option `TTOOLS_WP_OPTION` is defined.

I have searched for `add_option` and `update_option` but not found it somewhere.

Below is the code which causes an issue:
```
$options = get_option( TTOOLS_WP_OPTION );
$value   = $options['additional_language'];
```

_Sidenote: I have installed the plugin with CLI which may the reason behind this error (Not sure.)_

Nice plugin.

**Comment by pedro-mendonca** [comment] 2020-06-12 09:55
Hi @maheshwaghmare 
Thanks for your report.
The `TTOOLS_WP_OPTION` is set in the [main plugin file](https://github.com/pedro-mendonca/Translation-Stats/blob/master/translation-stats.php#L41).

There are no `add_option` and `update_option` because it is all done through the [settings_API](https://github.com/pedro-mendonca/Translation-Tools/blob/master/includes/class-ttools-options-general.php#L112).

I guess that error is being shown because you didn't select an option from the extra _no language packs_ dropdown.
Can you confirm this?

Thank you

**Comment by pedro-mendonca** [comment] 2020-06-12 11:07
I'm not being able to reproduce that exact error.
Please try changing the line below from:
`$value   = $options['additional_language'];`
to
`$value   = $options ? $options['additional_language'] : false;`

Please let me know if it solved your error.

**Comment by maheshwaghmare** [comment] 2020-06-12 12:47
Actually I have just install and activate the plugin and get that error.

I have not store any settings. Not sure for which reason I get this error. Ill reconfirm it and let you know soon.

**Comment by pedro-mendonca** [comment] 2020-06-12 13:11
The error is because it is looking for that setting to show the selected option, or else it just shows the blank option.
I've fixed it and will release the fix.

**Comment by pedro-mendonca** [comment] 2020-06-12 14:25
@maheshwaghmare please check it it's solved in the version 1.0.1.
Thanks :)

**Comment by pedro-mendonca** [comment] 2020-09-14 14:50
@maheshwaghmare I'll close this issue as it is fixed.
Feel free to reopen if you still find any dificulties. :)

**Closed by pedro-mendonca** 2020-09-14 14:50 UTC

**Comment by maheshwaghmare** [comment] 2020-09-14 15:01
Oh! I miss the recent notification. And, I think yes. It is fixed now.

**Comment by pedro-mendonca** [comment] 2020-09-14 15:07
Thanks 👍
